version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: book
      MYSQL_USER: spring
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  spring:
    image: ssafysong/book:1.0.0
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
